Add guide for Triggers and Functions
RedisInsight/Guides pull request #49
Opened 2023-07-29 20:40 UTC by thomascaudron

Added a guide for Triggers and Functions containing:
- An introduction
- Uploading functions
- Working with KeySpace triggers
- Additional information

2023-07-31 14:08 UTC, dwdougherty requested changes

2023-07-31 14:08 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/introduction.md
> +**Triggers and Functions** is a JavaScript engine for data processing in Redis. Triggers and Functions support on-demand and event-driven processing of Redis data. To use Triggers and Functions, you
```suggestion
**Triggers and Functions** is a JavaScript engine for data processing in Redis. This engine enables both on-demand and event-driven processing of Redis data. To use Triggers and Functions, you need to write functions that describe how the data should be processed. Then, you register triggers that define the keyspace notifications or streams that will execute these functions.
```

2023-07-31 14:08 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/keyspace-triggers.md
> +Functions can react to events within Redis with key space triggers. Most of the events are triggered by command invocation but includes also events for when a key is expired or evicted from the datab
```suggestion
Functions within Redis can respond to events using key space triggers. While the majority of these events are initiated by command invocations, they also include events that occur when a key expires or is removed from the database.
```

2023-07-31 14:08 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/keyspace-triggers.md
> +Add a new hash to.
```suggestion
Add a new hash.
```

2023-07-31 14:08 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/loading-a-library.md
> +When creating a new library we add the code to the command. The code need to contain a prologue where we define which engine is used, the name of the library and the minimum API version to use.
```suggestion
When creating a new library we add the code using the `TFUNCTION LOAD` command. The code needs to contain a prologue where we define which engine is used, the name of the library, and the minimum API version to use.
```

2023-07-31 14:08 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/loading-a-library.md
> +To update the library, add the replace argument.
```suggestion
To update the library, add `REPLACE` to the `LOAD` command.
```

2023-07-31 14:08 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/loading-a-library.md
> +Now run the command with an additional argument
```suggestion
Now run the command with an additional argument.
```

2023-08-01 07:04 UTC, ViktarStarastsenka commented on src/quick-guides/triggers-and-functions/keyspace-triggers.md
> +Add a new hash.
maybe add a bit of a business explanation here?

2023-08-01 07:04 UTC, ViktarStarastsenka commented on src/quick-guides/triggers-and-functions/learn-more.md
> +* [Triggers and Functions Preview]()
please add a link

2023-08-01 07:04 UTC, ViktarStarastsenka commented on src/quick-guides/triggers-and-functions/learn-more.md
> +* [Redis OSS Home](https://redis.io/docs/interact/programmability/triggers-and-functions)
when this documentation will be released? it may make sense to remove any non-existing links and add them later when the pages are published

2023-08-02 13:48 UTC, dwdougherty approved these changes

2023-08-03 13:48 UTC, ViktarStarastsenka submitted a review, later dismissed

2023-08-03 13:48 UTC, ViktarStarastsenka commented on src/quick-guides/triggers-and-functions/introduction.md
> +* Automatic Expire.
let's remove dots in this list

2023-08-03 13:48 UTC, ViktarStarastsenka commented on src/quick-guides/triggers-and-functions/introduction.md
> +[Triggers and Functions](https://redis.io/docs/interact/programmability/triggers-and-functions) >=2.0 \
```suggestion
[Triggers and Functions](https://redis.io/docs/interact/programmability/triggers-and-functions/?utm_source=redis\&utm_medium=app\&utm_campaign=redisinsight_triggers_and_functions_guide) >=2.0 \
```

2023-08-23 11:22 UTC, ViktarStarastsenka commented on src/quick-guides/triggers-and-functions/introduction.md
> +* [Automatic Expire](https://redis.io/docs/interact/programmability/triggers-and-functions/examples/#automatic-expiration)
let's add UTM parameters to these 3 links as well

2023-09-12 13:50 UTC, ViktarStarastsenka commented
@dwdougherty , please review it one more time

2023-09-13 21:38 UTC, dwdougherty requested changes
Just a few changes...

2023-09-13 21:38 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/keyspace-triggers.md
> +Functions within Redis can respond to events using key space triggers. While the majority of these events are initiated by command invocations, they also include events that occur when a key expires
```suggestion
Functions within Redis can respond to events using keyspace triggers. While the majority of these events are initiated by command invocations, they also include events that occur when a key expires or is removed from the database.
```

2023-09-13 21:38 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/keyspace-triggers.md
> +For the full list of supported events, please refer to the [Redis Key Space notifications page](https://redis.io/docs/manual/keyspace-notifications/#events-generated-by-different-commands/?utm_source
```suggestion
For the full list of supported events, see the [Redis Key Space notifications page](https://redis.io/docs/manual/keyspace-notifications/#events-generated-by-different-commands/?utm_source=redis\&utm_medium=app\&utm_campaign=redisinsight_triggers_and_functions_guide).
```

2023-09-13 21:38 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/introduction.md
> +**Triggers and Functions** can execute server-side JavaScript functions that are either triggered by a keyspace change, by a stream entry arrival, or by explicitly calling them. This empoweres develo
The word "whilst" is sooo last century! :)

```suggestion
**Triggers and Functions** can execute server-side JavaScript functions that are either triggered by a keyspace change, by a stream entry arrival, or by explicitly calling them. This empoweres developers to build and maintain real-time applications by moving business logic closer to the data, ensuring a lower latency while delivering the best developer experience.
```

2023-09-13 21:38 UTC, dwdougherty commented on src/quick-guides/triggers-and-functions/introduction.md
> +### PRE-REQUISITES
```suggestion
### Prerequisites
```

2023-09-14 08:17 UTC, ViktarStarastsenka commented on src/quick-guides/triggers-and-functions/introduction.md
> +### PRE-REQUISITES
let's use the "PRE-REQUISITES" since this is what is currently used in other guides/tutorials
we may need to change it everywhere at once

2023-09-15 15:19 UTC, ViktarStarastsenka approved these changes
LGTM

2023-09-15 15:44 UTC, dwdougherty approved these changes

2023-09-15 15:56 UTC, merged