Feature/new guides
RedisInsight/Guides pull request #9
Opened 2022-03-16 17:30 UTC by ViktarStarastsenka

Updated guides for the Enablement area

2022-03-17 12:05 UTC, LiorKogan approved these changes

2022-03-22 10:15 UTC, simonprickett requested changes

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/probabilistic-data-structures/top-k.md
> +Returns “nil” if no change to Top-K list occurred, else returns item dropped from the list.
```suggestion
This returns “nil” if no change to Top-K list occurred.  If the item modified entered the Top-K list as a result, then the item dropped from the list to make room for it is returned.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/probabilistic-data-structures/top-k.md
> +Now we can check whether an item is one of Top-K items or not.
```suggestion
Now we can check whether an item is one of the Top-K items or not.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/probabilistic-data-structures/top-k.md
> +Let's see the full list of items in our Top K list.
```suggestion
Let's see the full list of items in our Top-K list.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/probabilistic-data-structures/top-k.md
> +You can see the number of required items (k), width, depth and decay values in your TopK filter.
```suggestion
You can see the number of required items (k), width, depth and decay values in your Top-K.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/probabilistic-data-structures/top-k.md
> +```redis Information About The Filter
```suggestion
```redis Get Information About The Top-K
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/aggregation.md
> +You can use the GROUPBY and REDUCE options to group results of time series by label and apply an additional aggregation.
```suggestion
You can use the `GROUPBY` and `REDUCE` options to group results of time series by label and apply an additional aggregation.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/compactions.md
> +With compactions, you could aggregate the data by every minute in order to compact data points and reduce the database size (for example, if you have collected more than one billion data points in a
```suggestion
With compactions, you could aggregate the data into one minute buckets in order to compact data points and reduce the database size (for example, if you have collected more than one billion data points in a day).
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/compactions.md
> +No data rewriting on the original time series - the compaction happens in a new series, while the original one stays the same.
```suggestion
Data rewriting is not performed on the original time series - the compaction happens in a new series, while the original one stays the same.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/compactions.md
> +If no longer needed, you can just delete a compaction rule.
```suggestion
Compaction rules can be deleted when no longer needed:
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/creating-a-time-series.md
> +We can get all the information and statistics about time series created.
```suggestion
Use the `TS.INFO` command to get all the information and statistics about a time series.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/creating-a-time-series.md
> +```redis Read
```suggestion
```redis Get Time Series Information
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/creating-a-time-series.md
> +DEL sensor1 // Deletes the entire time series
```suggestion
DEL sensor1 // Deletes the entire time series immediately
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/creating-a-time-series.md
> +    sensor1 // Keyname for the second time series, which can be a different one
```suggestion
    sensor1 // Keyname for the second time series, which can be different
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/creating-a-time-series.md
> +    * // Will use  the current timestamp
```suggestion
    * // Will use the current timestamp
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/creating-a-time-series.md
> +You can also update existing time series.
```suggestion
You can also update an existing time series using the `TS.ALTER` command.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/creating-a-time-series.md
> +```redis Update
```suggestion
```redis Update a Time Series
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/filtering.md
> +We also can filter the data out based on timestamps.
```suggestion
We also can filter the data based on timestamps.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/introduction.md
> +A (free and ready to use) instance on [Redis Cloud](https://redis.com/try-free/?utm_source=redis\&utm_medium=app\&utm_campaign=redisinsight_doc_guide).
```suggestion
A free Redis Stack instance on [Redis Cloud](https://redis.com/try-free/?utm_source=redis\&utm_medium=app\&utm_campaign=redisinsight_doc_guide).
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/learn-more.md
> +* [More on Redis University](https://university.redis.com/)
```suggestion
```

We don't currently have RedisTimeSeries content on University.

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/time-series/learn-more.md
> +- [RedisTimeSeries at Redis Forum](https://forum.redis.com/c/modules/redistimeseries/62)
Suggest moving forum to the bottom of the list as it's the least active channel.  Discord and GitHub should be at the top.

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/vector-similarity-search/create-vector-index.md
> +Use this type of index for Exact Nearest Neighbor search. Best for accuracy.
```suggestion
Use this type of index for Exact Nearest Neighbor search. This type of index is best for accuracy.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/vector-similarity-search/create-vector-index.md
> +The "vector representation" of an image, also known as an embedding", is a list of numbers that provide a representation of the image.
```suggestion
The "vector representation" of an image, also known as an "embedding", is a list of numbers that provide a representation of the image.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/vector-similarity-search/introduction.md
> +**You can index and query vector data stored in Redis [Hashes](https://redis.io/topics/data-types#hashes)**  This capability extends RediSearch's abilities to index NUMERIC, GEO and TEXT data stored
```suggestion
**You can index and query vector data stored in Redis [Hashes](https://redis.io/topics/data-types#hashes)**  This capability extends RediSearch's abilities to index NUMERIC, GEO and TEXT data stored in hashes.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/vector-similarity-search/introduction.md
> +A (free and ready to use) instance on [Redis Cloud](https://redis.com/try-free/?utm_source=redis\&utm_medium=app\&utm_campaign=redisinsight_doc_guide).
```suggestion
A free Redis Stack instance on [Redis Cloud](https://redis.com/try-free/?utm_source=redis\&utm_medium=app\&utm_campaign=redisinsight_doc_guide).
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/vector-similarity-search/load-vectors.md
> +Note that the product data will be indexed automatically as you HSET the product data!
```suggestion
Note that the product data will be indexed automatically as you `HSET` the product data!
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/vector-similarity-search/load-vectors.md
> +Two mobile phone covers
```suggestion
Two mobile phone covers.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/vector-similarity-search/query-vectors.md
> +**SPOILER ALERT:**  It's not the chair, patio light or the two-seater sofa
```suggestion
**SPOILER ALERT:**  It's not the chair, patio light or the two-seater sofa.
```

2022-03-22 10:15 UTC, simonprickett commented on guides/quick-guides/vector-similarity-search/query-vectors.md
> +Now let's further filter the visual similarity queries to only match products with a price between 70 & 80
```suggestion
Now let's further filter the visual similarity queries to only match products with a price between 70 & 80.
```

2022-03-22 10:15 UTC, simonprickett commented
Been through and left suggestions throughout.

2022-03-22 11:08 UTC, K-Jo commented on guides/quick-guides/document/learn-more.md
> +- [RediSearch on Discord](https://discord.com/channels/697882427875393627/732335216068132995)
agreed

2022-03-22 13:33 UTC, ViktarStarastsenka commented on guides/quick-guides/probabilistic-data-structures/bloom-filter.md
> +Bloom filters are used to determine, with a high degree of certainty, whether an element is a member of a set. They typically exhibit better performance and scalability when inserting items.
updated

2022-03-23 05:39 UTC, arthosofteq approved these changes

2022-03-23 05:41 UTC, merged